name: Go tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Update with desired Go version

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Build and Test
        run: |
          go build -v ./...
          go test -v ./...